version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    # Disable version updates for actions (doesn't impact security updates)
    # https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#open-pull-requests-limit
    open-pull-requests-limit: 0

  - package-ecosystem: 'nuget'
    directory: '/'
    schedule:
      interval: 'daily'
    # Disable version updates for nuget (doesn't impact security updates)
    # https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#open-pull-requests-limit
    open-pull-requests-limit: 0
