name: Component Detection CI

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      OFFICIAL_BUILD: 'True'
      # Set the build number in MinVer.
      MINVERBUILDMETADATA: build.${{github.run_number}}

    steps:
    - uses: actions/checkout@v2.3.2
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: dotnet restore
      run: dotnet restore

    - name: Build and publish
      run: dotnet publish -o dist --no-self-contained -c Release ./src/Microsoft.ComponentDetection

    - name: Create temporary folder for release
      run: mkdir ./dist-release

    - name: Tar the output
      run: tar -C ./dist -cvf ./dist-release/component-detection.tar.gz .

    - name: Add NuGet publication source for Github packages
      if: github.event_name == 'release'
      run: dotnet nuget add source https://nuget.pkg.github.com/microsoft/index.json --password $GITHUB_TOKEN --username notused --store-password-in-clear-text --name cgwriter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate NuGet packages
      if: github.event_name == 'release'
      run: dotnet pack -o dist-nuget -c Release

      # dotnet nuget push seems to have some probs, use curl for GH
    - name: Publish nuget
      if: github.event_name == 'release'
      run: |
           for f in ./dist-nuget/*.nupkg
           do
             curl -vX PUT -u "[user]:${{ secrets.GITHUB_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/microsoft/
           done
      shell: bash
