name: "Generate docs"

on:
  push:
    branches:
      - main
    paths:
      - "src/Microsoft.ComponentDetection.Orchestrator/ArgumentSets/*.cs"

permissions:
  contents: read

jobs:
  gen-docs:
    permissions:
      contents: write # for stefanzweifel/git-auto-commit-action to push code in repo
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1

      - name: Generate docs
        run: |
          touch version.json
          touch version_dev.json

          # Run CLI
          dotnet run -p src/Microsoft.ComponentDetection help scan 2> help.txt || true
          cat <<EOF > docs/detector-arguments.md
          # Detector arguments

          \`\`\`shell
          dotnet run -p './src/Microsoft.ComponentDetection' help scan
          \`\`\`

          \`\`\`
          $(tail --lines=+4 help.txt)
          \`\`\`
          EOF

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
        with:
          commit_message: "Update docs"
          file_pattern: "*.md"
