name: Test Linux Container Scanning

on: [pull_request]

jobs:
  test-linux:

    runs-on: ubuntu-latest

    env:
      OFFICIAL_BUILD: 'True'

    steps:
    - uses: actions/checkout@v2.3.2
      with:
          fetch-depth: 0

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: dotnet restore
      run: dotnet restore

    - name: Build and publish
      run: dotnet publish -o dist --no-self-contained -c Release ./src/Microsoft.ComponentDetection

    - name: Make empty directory
      working-directory: src/Microsoft.ComponentDetection/
      run: mkdir empty

    - name: Preload node image to scan
      run: docker pull node:slim

    - name: Preload golang image to scan
      run: docker pull golang:alpine
  
    - name: Preload ubuntu image to scan
      run: docker pull ubuntu@sha256:2b90cad5ded7946db07a28252618b9c8b7f4f103fc39266bcc795719d1362d40

    - name: Preload distroless image to scan
      run: docker pull gcr.io/distroless/nodejs-debian10

    - name: Test linux scanner
      working-directory: src/Microsoft.ComponentDetection/
      run: dotnet run scan --Verbosity Verbose --SourceDirectory empty --DockerImagesToScan node:slim,golang:alpine,ubuntu@sha256:2b90cad5ded7946db07a28252618b9c8b7f4f103fc39266bcc795719d1362d40,alpine:latest,gcr.io/distroless/nodejs-debian10
